version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 966084525349.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t mynode:latest .
      - docker tag mynode:latest <ECR-REPO-NAME>
  post_build:
    commands:
      - docker push <ECR-REPO-NAME>
      - printf '[{"name":"mynode","imageUri":"%s"}]' <ECR-REPo-NAME> > imagedefinitions.json
artifacts:
  files: imagedefinitions.json